import Head from "next/head";
import Brand from "../components/Brand";
import FormSignin from "../components/FormSignin";
import Navbar from "../components/Navbar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Semina || Signin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<section className="bg-navy">
				<Navbar />
			</section>
			<section className="login header bg-navy">
				<div className="container">
					<div className="d-flex flex-column align-items-center hero gap-5">
						<div>
							<div className="hero-headline text-start">Sign In</div>
						</div>
						<FormSignin />
					</div>
				</div>
			</section>
			<Brand className="pt-0 bg-navy" />
		</>
	);
}

export async function getServerSideProps(context) {
	/**
	 * Tahap ini menggunakan server side dengan tujuan untuk mengecek tokennya ada atau tidak, jika tokennya ada, maka akan di direct ke home ('/')
	 */
	const { token } = context.req.cookies;

	if (token) {
		return {
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}

	return {
		props: {},
	};
}
